// Copyright 2013-2014 Naked Objects Group Ltd
// Licensed under the Apache License, Version 2.0(the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
var NakedObjects;
(function (NakedObjects) {
    // custom configuration for a particular implementation 
    // path to Restful API -  in this case generated by the same project
    var appPath = "http://localhost:59949/rest";
    function getAppPath() {
        if (appPath.charAt(appPath.length - 1) === "/") {
            return appPath.length > 1 ? appPath.substring(0, appPath.length - 1) : "";
        }
        return appPath;
    }
    NakedObjects.getAppPath = getAppPath;
    NakedObjects.logoffUrl = appPath + "/Account/Logoff";
    NakedObjects.postLogoffUrl = "/#/gemini/home";
    NakedObjects.defaultPageSize = 20; // can be overridden by server 
    NakedObjects.listCacheSize = 5;
    NakedObjects.shortCutMarker = "___";
    //Add in any other long strings that commonly appear in your Urls, to replace them with the shortCutMarker plus number index.
    NakedObjects.urlShortCuts = ["http://localhost:59949/rest", "ExampleModel"];
    NakedObjects.keySeparator = "--"; //Do not change this unless you change the Restful API configuration to match
    NakedObjects.objectColor = "object-color";
    NakedObjects.linkColor = "link-color";
    NakedObjects.autoLoadDirty = true;
    NakedObjects.showDirtyFlag = false || !NakedObjects.autoLoadDirty;
    // caching constants: do not change unless you know what you're doing 
    NakedObjects.httpCacheDepth = 50;
    NakedObjects.transientCacheDepth = 4;
    NakedObjects.recentCacheDepth = 20;
    // checks for inconsistencies in url
    NakedObjects.doUrlValidation = false;
    NakedObjects.leftClickHomeAlwaysGoesToSinglePane = true;
})(NakedObjects || (NakedObjects = {}));
//# sourceMappingURL=nakedobjects.config.js.map