//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NakedObjects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NakedObjects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NakedObjects() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NakedObjects.Resources.NakedObjects", typeof(NakedObjects).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DUPLICATE.
        /// </summary>
        public static string _DUPLICATE {
            get {
                return ResourceManager.GetString("_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add nothing (null) to a collection.
        /// </summary>
        public static string AddNullError {
            get {
                return ResourceManager.GetString("AddNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object already persistent: {0}.
        /// </summary>
        public static string AlreadyPersistentMessage {
            get {
                return ResourceManager.GetString("AlreadyPersistentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always disabled.
        /// </summary>
        public static string AlwaysDisabled {
            get {
                return ResourceManager.GetString("AlwaysDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always hidden.
        /// </summary>
        public static string AlwaysHidden {
            get {
                return ResourceManager.GetString("AlwaysHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found more than one method named {0} in {1}.
        /// </summary>
        public static string AmbiguousMethodError {
            get {
                return ResourceManager.GetString("AmbiguousMethodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application error.
        /// </summary>
        public static string ApplicationErrorTitle {
            get {
                return ResourceManager.GetString("ApplicationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert {0} to array of {1}.
        /// </summary>
        public static string ArrayConvertError {
            get {
                return ResourceManager.GetString("ArrayConvertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly {0} not found by Code First configuration  .
        /// </summary>
        public static string AssemblyNotFound {
            get {
                return ResourceManager.GetString("AssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialise AzMan Store Application: {0} URL: {1}.
        /// </summary>
        public static string AzmanFail {
            get {
                return ResourceManager.GetString("AzmanFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounded.
        /// </summary>
        public static string Bounded {
            get {
                return ResourceManager.GetString("Bounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create an instance of an abstract class: {0}.
        /// </summary>
        public static string CannotCreateAbstract {
            get {
                return ResourceManager.GetString("CannotCreateAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find key for {0}.
        /// </summary>
        public static string CannotFindKeyMessage {
            get {
                return ResourceManager.GetString("CannotFindKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot format value {0} as {1}.
        /// </summary>
        public static string CannotFormat {
            get {
                return ResourceManager.GetString("CannotFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class {0} must be of the type {1}.
        /// </summary>
        public static string ClassTypeMismatch {
            get {
                return ResourceManager.GetString("ClassTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock already set up.
        /// </summary>
        public static string ClockSetupMessage {
            get {
                return ResourceManager.GetString("ClockSetupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0}.
        /// </summary>
        public static string CollectionTitleEmpty {
            get {
                return ResourceManager.GetString("CollectionTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string CollectionTitleMany {
            get {
                return ResourceManager.GetString("CollectionTitleMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 {0}.
        /// </summary>
        public static string CollectionTitleOne {
            get {
                return ResourceManager.GetString("CollectionTitleOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloaded {0} collection.
        /// </summary>
        public static string CollectionTitleUnloaded {
            get {
                return ResourceManager.GetString("CollectionTitleUnloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: {0} is complex and so must be annotated with an Inline attribute.
        /// </summary>
        public static string ComplexTypeErrorMessage {
            get {
                return ResourceManager.GetString("ComplexTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound key: {0} does not contain an object type.
        /// </summary>
        public static string CompoundKeyDoesNotContainType {
            get {
                return ResourceManager.GetString("CompoundKeyDoesNotContainType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound key: {0} has no key values.
        /// </summary>
        public static string CompoundKeyHasNoKeyValues {
            get {
                return ResourceManager.GetString("CompoundKeyHasNoKeyValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object you were viewing was out of date. Your action/edit has not been applied, you may return to the object which has now been reloaded and try your action/edit again. 
        ///Original Error: {0}.
        /// </summary>
        public static string ConcurrencyErrorMessage {
            get {
                return ResourceManager.GetString("ConcurrencyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConcurrencyException.
        /// </summary>
        public static string ConcurrencyException {
            get {
                return ResourceManager.GetString("ConcurrencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update conflict. Your changes have NOT been saved. That object&apos;s details have been reloaded. None of your changes have been made. You may try to make your changes again, if they are still valid..
        /// </summary>
        public static string ConcurrencyMessage {
            get {
                return ResourceManager.GetString("ConcurrencyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrency Error.
        /// </summary>
        public static string ConcurrencyTitle {
            get {
                return ResourceManager.GetString("ConcurrencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataUpdateException.
        /// </summary>
        public static string DataUpdateException {
            get {
                return ResourceManager.GetString("DataUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed {1} at {2}{3}{4}{5} ~ {6}.
        /// </summary>
        public static string DataUpdateMessage {
            get {
                return ResourceManager.GetString("DataUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Update Error.
        /// </summary>
        public static string DataUpdateTitle {
            get {
                return ResourceManager.GetString("DataUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled once persisted.
        /// </summary>
        public static string DisabledOncePersisted {
            get {
                return ResourceManager.GetString("DisabledOncePersisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled until persisted.
        /// </summary>
        public static string DisabledUntilPersisted {
            get {
                return ResourceManager.GetString("DisabledUntilPersisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a reference for disposing an object.
        /// </summary>
        public static string DisposeReferenceError {
            get {
                return ResourceManager.GetString("DisposeReferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain class: {0} must be marked as public so it can be introspected.
        /// </summary>
        public static string DomainClassReflectionError {
            get {
                return ResourceManager.GetString("DomainClassReflectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty string&gt;.
        /// </summary>
        public static string EmptyString {
            get {
                return ResourceManager.GetString("EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of commit cycles exceeded. Either increase MaxCommitCycles on installer or identify Updated/Persisted loop. Possible types : {0}.
        /// </summary>
        public static string EntityCommitError {
            get {
                return ResourceManager.GetString("EntityCommitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Entity Framework context for type: {0} Possible causes:
        ///1. Missing connection string in App.config
        ///2. Mismatch between class properties and entity properties
        ///3. Attempting to persist a non-persisted type.
        /// </summary>
        public static string EntityContextError {
            get {
                return ResourceManager.GetString("EntityContextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error finding class {0}.
        /// </summary>
        public static string ErrorFindingClass {
            get {
                return ResourceManager.GetString("ErrorFindingClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure reading help file: {0}.
        /// </summary>
        public static string ErrorReadingHelpFile {
            get {
                return ResourceManager.GetString("ErrorReadingHelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception has occurred.  Please consider uploading the following information, along with a full stack trace, to help with a support query and to help improve the product.
        ///
        ///.
        /// </summary>
        public static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create instance of type {0}.
        /// </summary>
        public static string FailedToCreateInstance {
            get {
                return ResourceManager.GetString("FailedToCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find an instance of {0} with title {1}.
        /// </summary>
        public static string FailedToFindInstance {
            get {
                return ResourceManager.GetString("FailedToFindInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load class {0}.
        /// </summary>
        public static string FailedToLoadClass {
            get {
                return ResourceManager.GetString("FailedToLoadClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load class {0} From Assembly {1}.
        /// </summary>
        public static string FailedToLoadFromAssembly {
            get {
                return ResourceManager.GetString("FailedToLoadFromAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field disabled as object cannot be changed.
        /// </summary>
        public static string FieldDisabled {
            get {
                return ResourceManager.GetString("FieldDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field disabled once object persisted.
        /// </summary>
        public static string FieldDisabledOnce {
            get {
                return ResourceManager.GetString("FieldDisabledOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field disabled until object persisted.
        /// </summary>
        public static string FieldDisabledUntil {
            get {
                return ResourceManager.GetString("FieldDisabledUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field not editable.
        /// </summary>
        public static string FieldNotEditable {
            get {
                return ResourceManager.GetString("FieldNotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field not editable now that object is persistent.
        /// </summary>
        public static string FieldNotEditableNow {
            get {
                return ResourceManager.GetString("FieldNotEditableNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field not editable until the object is persistent.
        /// </summary>
        public static string FieldNotEditableUntil {
            get {
                return ResourceManager.GetString("FieldNotEditableUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object not found in store with oid {0}.
        /// </summary>
        public static string FindObjectMessage {
            get {
                return ResourceManager.GetString("FindObjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixtures specified, but none loaded.
        /// </summary>
        public static string FixturesError {
            get {
                return ResourceManager.GetString("FixturesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found more than one instance of {0} with title {1}: {2}.
        /// </summary>
        public static string FoundMultipleInstances {
            get {
                return ResourceManager.GetString("FoundMultipleInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden once persisted.
        /// </summary>
        public static string HiddenOncePersisted {
            get {
                return ResourceManager.GetString("HiddenOncePersisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden until persisted.
        /// </summary>
        public static string HiddenUntilPersisted {
            get {
                return ResourceManager.GetString("HiddenUntilPersisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immutable.
        /// </summary>
        public static string Immutable {
            get {
                return ResourceManager.GetString("Immutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} objects can never be edited!.
        /// </summary>
        public static string ImmutableMessage {
            get {
                return ResourceManager.GetString("ImmutableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} objects can not be edited once they are persistent.
        /// </summary>
        public static string ImmutableOncePersistedMessage {
            get {
                return ResourceManager.GetString("ImmutableOncePersistedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} objects cannot be edited until they have been persisted.
        /// </summary>
        public static string ImmutableUntilPersistedMessage {
            get {
                return ResourceManager.GetString("ImmutableUntilPersistedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete entry; difference required.
        /// </summary>
        public static string IncompleteEntry {
            get {
                return ResourceManager.GetString("IncompleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument.
        /// </summary>
        public static string InvalidArgument {
            get {
                return ResourceManager.GetString("InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments.
        /// </summary>
        public static string InvalidArguments {
            get {
                return ResourceManager.GetString("InvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid difference specified.
        /// </summary>
        public static string InvalidDifference {
            get {
                return ResourceManager.GetString("InvalidDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entry.
        /// </summary>
        public static string InvalidEntry {
            get {
                return ResourceManager.GetString("InvalidEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectFinder does not support {0} as a key type..
        /// </summary>
        public static string InvalidKeyType {
            get {
                return ResourceManager.GetString("InvalidKeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data for logical, expected 1 byte, got {0}.
        /// </summary>
        public static string InvalidLogicalLength {
            get {
                return ResourceManager.GetString("InvalidLogicalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data for logical, expected &apos;T&apos;, &apos;F&apos; or &apos;N, but got {0}.
        /// </summary>
        public static string InvalidLogicalType {
            get {
                return ResourceManager.GetString("InvalidLogicalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid name.
        /// </summary>
        public static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key: &apos;{0}&apos; can not be parsed as a {1}.
        /// </summary>
        public static string KeyTypeMismatch {
            get {
                return ResourceManager.GetString("KeyTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory.
        /// </summary>
        public static string Mandatory {
            get {
                return ResourceManager.GetString("Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not fit mask.
        /// </summary>
        public static string MaskError {
            get {
                return ResourceManager.GetString("MaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not match the mask &apos;{1}&apos;.
        /// </summary>
        public static string MaskMismatch {
            get {
                return ResourceManager.GetString("MaskMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeds maximum length.
        /// </summary>
        public static string MaximumLengthMessage {
            get {
                return ResourceManager.GetString("MaximumLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value exceeds the maximum length of {0}.
        /// </summary>
        public static string MaximumLengthMismatch {
            get {
                return ResourceManager.GetString("MaximumLengthMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entry must be provided.
        /// </summary>
        public static string MissingEntryError {
            get {
                return ResourceManager.GetString("MissingEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field type for &apos;{0}&apos; must exist.
        /// </summary>
        public static string MissingFieldType {
            get {
                return ResourceManager.GetString("MissingFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} has multi-part key.
        /// </summary>
        public static string MultiPartKeyMessage {
            get {
                return ResourceManager.GetString("MultiPartKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must always be set.
        /// </summary>
        public static string NameNotSetMessage {
            get {
                return ResourceManager.GetString("NameNotSetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No authenticator available for processing {0}.
        /// </summary>
        public static string NoAuthenticatorFor {
            get {
                return ResourceManager.GetString("NoAuthenticatorFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No authenticators specified.
        /// </summary>
        public static string NoAuthenticators {
            get {
                return ResourceManager.GetString("NoAuthenticators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a IEntityWithChangeTracker ({1}).
        /// </summary>
        public static string NoChangeTrackerMessage {
            get {
                return ResourceManager.GetString("NoChangeTrackerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entity connection strings in App.config file.
        /// </summary>
        public static string NoConnectionString {
            get {
                return ResourceManager.GetString("NoConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} needs a container - either create with NewTransientInstance or inject manually.
        /// </summary>
        public static string NoContainerMessage {
            get {
                return ResourceManager.GetString("NoContainerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No help available (no file found).
        /// </summary>
        public static string NoHelpFile {
            get {
                return ResourceManager.GetString("NoHelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} does not have an integer key.
        /// </summary>
        public static string NoIntegerKey {
            get {
                return ResourceManager.GetString("NoIntegerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object: {0} has no Keys defined.
        /// </summary>
        public static string NoKeysDefined {
            get {
                return ResourceManager.GetString("NoKeysDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching objects found.
        /// </summary>
        public static string NoMatchPlural {
            get {
                return ResourceManager.GetString("NoMatchPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching object found.
        /// </summary>
        public static string NoMatchSingular {
            get {
                return ResourceManager.GetString("NoMatchSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No perspective {0}.
        /// </summary>
        public static string NoPerspective {
            get {
                return ResourceManager.GetString("NoPerspective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not been proxied ({1}).
        /// </summary>
        public static string NoProxyMessage {
            get {
                return ResourceManager.GetString("NoProxyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No services specified.
        /// </summary>
        public static string NoServices {
            get {
                return ResourceManager.GetString("NoServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No stacktrace available).
        /// </summary>
        public static string NoStackTrace {
            get {
                return ResourceManager.GetString("NoStackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a logical value {0}.
        /// </summary>
        public static string NotALogical {
            get {
                return ResourceManager.GetString("NotALogical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a number.
        /// </summary>
        public static string NotANumber {
            get {
                return ResourceManager.GetString("NotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitably annotated title property on class: {0}.
        /// </summary>
        public static string NoTitleAnnotation {
            get {
                return ResourceManager.GetString("NoTitleAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object not persistent: {0}.
        /// </summary>
        public static string NotPersistentMessage {
            get {
                return ResourceManager.GetString("NotPersistentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use NewTransientInstance for an InLine type..
        /// </summary>
        public static string NoTransientInline {
            get {
                return ResourceManager.GetString("NoTransientInline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of keys provided does not match the number of keys specified for type: {0}.
        /// </summary>
        public static string NumberOfkeysMismatch {
            get {
                return ResourceManager.GetString("NumberOfkeysMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        public static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be assigned to: {1}.
        /// </summary>
        public static string ObjectCannotBeAssigned {
            get {
                return ResourceManager.GetString("ObjectCannotBeAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object has multiple properties with suffix: {0}.
        /// </summary>
        public static string ObjectMultiplePropertiesMessage {
            get {
                return ResourceManager.GetString("ObjectMultiplePropertiesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object has no properties with suffix: {0}.
        /// </summary>
        public static string ObjectNoPropertiesMessage {
            get {
                return ResourceManager.GetString("ObjectNoPropertiesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object not valid.
        /// </summary>
        public static string ObjectNotValid {
            get {
                return ResourceManager.GetString("ObjectNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        public static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value &apos;{0}&apos; out of valid range {1} to {2}.
        /// </summary>
        public static string OutOfRange {
            get {
                return ResourceManager.GetString("OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Range.
        /// </summary>
        public static string OutOfRangeMessage {
            get {
                return ResourceManager.GetString("OutOfRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not match pattern.
        /// </summary>
        public static string PatternMessage {
            get {
                return ResourceManager.GetString("PatternMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have both Persisting and Saving methods - please remove Saving.
        /// </summary>
        public static string PersistingSavingError {
            get {
                return ResourceManager.GetString("PersistingSavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to create persistor for second context; persistor only works for single user systems.
        /// </summary>
        public static string PersistorErrorMessage {
            get {
                return ResourceManager.GetString("PersistorErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} not in a valid state to be persisted - {2}.
        /// </summary>
        public static string PersistStateError {
            get {
                return ResourceManager.GetString("PersistStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed during post save processing: {0}.
        /// </summary>
        public static string PostSaveError {
            get {
                return ResourceManager.GetString("PostSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1} is invalid: {2}.
        /// </summary>
        public static string PropertyInvalid {
            get {
                return ResourceManager.GetString("PropertyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mandatory property ({0}.{1}) is empty.
        /// </summary>
        public static string PropertyMandatory {
            get {
                return ResourceManager.GetString("PropertyMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all properties must be made virtual/Overrideable and all collection properties should be of type ICollection&lt;T&gt;.
        /// </summary>
        public static string ProxyExplanation {
            get {
                return ResourceManager.GetString("ProxyExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this may be because domain code is adding a transient to a persistent collection
        ///- stack trace of this exception should show domain code at fault if this is the case.
        ///Otherwise check all properties are virtual/Overrideable and all collection properties are of type ICollection&lt;T&gt;.
        /// </summary>
        public static string ProxyExplanationTransient {
            get {
                return ResourceManager.GetString("ProxyExplanationTransient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query would produce {0} objects. Only the first {1} will be shown.
        /// </summary>
        public static string QueryFilterMessage {
            get {
                return ResourceManager.GetString("QueryFilterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is outside the range {0} to {1}.
        /// </summary>
        public static string RangeMismatch {
            get {
                return ResourceManager.GetString("RangeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove nothing (null) from a collection.
        /// </summary>
        public static string RemoveNullError {
            get {
                return ResourceManager.GetString("RemoveNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require one argument.
        /// </summary>
        public static string RequireOneArgument {
            get {
                return ResourceManager.GetString("RequireOneArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatch of types on value semantic provider, expected {0} but was {1} on {2}.
        /// </summary>
        public static string SemanticProviderMismatch {
            get {
                return ResourceManager.GetString("SemanticProviderMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service object {0} should have no fields, but has: {1}.
        /// </summary>
        public static string ServiceObjectWithFieldsError {
            get {
                return ResourceManager.GetString("ServiceObjectWithFieldsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service already registered: {0}.
        /// </summary>
        public static string ServiceRegisterError {
            get {
                return ResourceManager.GetString("ServiceRegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create Code First DbContext.
        /// </summary>
        public static string StartPersistorErrorCodeFirst {
            get {
                return ResourceManager.GetString("StartPersistorErrorCodeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start persistor in Model/Database first mode.
        ///Connection string name={0} failed to load context. Ensure that the Assembly with the domain code for this connection string is loaded
        ///Typically reference a service or object in the Assembly in &apos;Services&apos; or &apos;Fixtures&apos; in the &apos;Run&apos; class
        ///or add a reference or an object or static in the Assembly in &apos;EnsureDomainAssembliesAreLoaded&apos; also in the &apos;Run&apos; class.
        /// </summary>
        public static string StartPersistorErrorMessage {
            get {
                return ResourceManager.GetString("StartPersistorErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title property: {0} on class: {1} must be a string to find by title.
        /// </summary>
        public static string TitlePropertyWrongType {
            get {
                return ResourceManager.GetString("TitlePropertyWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can&apos;t set a reference to a transient object from a persistent one: {0} (transient).
        /// </summary>
        public static string TransientErrorMessage {
            get {
                return ResourceManager.GetString("TransientErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t set field of persistent with a transient reference.
        /// </summary>
        public static string TransientFieldMessage {
            get {
                return ResourceManager.GetString("TransientFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can&apos;t set a reference to a transient object from a persistent one: {0} (persistent) -&gt; {1} (transient).
        /// </summary>
        public static string TransientReferenceError {
            get {
                return ResourceManager.GetString("TransientReferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using a reference to a transient object that has been persisted somewhere else (ie Framework has detected an attempt to use an object that has been replaced by a proxy)object : {0}.
        /// </summary>
        public static string TransientReferenceMessage {
            get {
                return ResourceManager.GetString("TransientReferenceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: {0} cannot be found.
        /// </summary>
        public static string TypeCannotBeFound {
            get {
                return ResourceManager.GetString("TypeCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a suitable type; must be a {0}.
        /// </summary>
        public static string TypeMismatchError {
            get {
                return ResourceManager.GetString("TypeMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported collection type {0}.
        /// </summary>
        public static string UnsupportedCollectionType {
            get {
                return ResourceManager.GetString("UnsupportedCollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled .
        /// </summary>
        public static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data update problem. Your changes have NOT been saved. Either correct changes and reattempt or cancel and continue. 
        ///Original Error: {0}.
        /// </summary>
        public static string UpdateErrorMessage {
            get {
                return ResourceManager.GetString("UpdateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload complete.
        /// </summary>
        public static string UploadComplete {
            get {
                return ResourceManager.GetString("UploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed.
        /// </summary>
        public static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Press Yes to upload this information, No to just view the stack trace, or Cancel to continue..
        /// </summary>
        public static string UploadMessage {
            get {
                return ResourceManager.GetString("UploadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error data upload.
        /// </summary>
        public static string UploadTitle {
            get {
                return ResourceManager.GetString("UploadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not check the version at this time.  Please try again later..
        /// </summary>
        public static string VersionCheckFailMessage {
            get {
                return ResourceManager.GetString("VersionCheckFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using version {0}. The latest available version is {1} ({2}).
        ///Download the latest version from the downloads page: 
        ///
        ///         {3}
        ///
        /// (This page should now be showing in your browser.).
        /// </summary>
        public static string VersionCheckReportMessage {
            get {
                return ResourceManager.GetString("VersionCheckReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This installation is the current version.  There in no need to update..
        /// </summary>
        public static string VersionCheckSuccessMessage {
            get {
                return ResourceManager.GetString("VersionCheckSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version check.
        /// </summary>
        public static string VersionCheckTitle {
            get {
                return ResourceManager.GetString("VersionCheckTitle", resourceCulture);
            }
        }
    }
}
