// Copyright Naked Objects Group Ltd, 45 Station Road, Henley on Thames, UK, RG9 1AT
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and limitations under the License.

using System;

namespace Microsoft.VisualStudio.TestPlatform {
    // this is a hack to fix a bug in MS test sdk
    // https://github.com/microsoft/vstest/issues/792

    public class TestSDKAutoGeneratedCodeAttribute : Attribute { }
}

namespace RestfulObjects.Test.Data {
    public static class Assert {
        public static void AreEqual(object o, object oo) { }
    }
}