//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NakedFramework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProgrammingModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgrammingModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NakedFramework.Resources.ProgrammingModel", typeof(ProgrammingModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find key for {0}.
        /// </summary>
        public static string CannotFindKeyMessage {
            get {
                return ResourceManager.GetString("CannotFindKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock already set up.
        /// </summary>
        public static string ClockSetupMessage {
            get {
                return ResourceManager.GetString("ClockSetupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound key: {0} does not contain an object type.
        /// </summary>
        public static string CompoundKeyDoesNotContainType {
            get {
                return ResourceManager.GetString("CompoundKeyDoesNotContainType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound key: {0} has no key values.
        /// </summary>
        public static string CompoundKeyHasNoKeyValues {
            get {
                return ResourceManager.GetString("CompoundKeyHasNoKeyValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectFinder does not support {0} as a key type..
        /// </summary>
        public static string InvalidKeyType {
            get {
                return ResourceManager.GetString("InvalidKeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid name.
        /// </summary>
        public static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key: &apos;{0}&apos; can not be parsed as a {1}.
        /// </summary>
        public static string KeyTypeMismatch {
            get {
                return ResourceManager.GetString("KeyTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} has multi-part key.
        /// </summary>
        public static string MultiPartKeyMessage {
            get {
                return ResourceManager.GetString("MultiPartKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} needs a container - either create with NewTransientInstance or inject manually.
        /// </summary>
        public static string NoContainerMessage {
            get {
                return ResourceManager.GetString("NoContainerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} does not have an integer key.
        /// </summary>
        public static string NoIntegerKey {
            get {
                return ResourceManager.GetString("NoIntegerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object: {0} has no Keys defined.
        /// </summary>
        public static string NoKeysDefined {
            get {
                return ResourceManager.GetString("NoKeysDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching objects found.
        /// </summary>
        public static string NoMatchPlural {
            get {
                return ResourceManager.GetString("NoMatchPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching object found.
        /// </summary>
        public static string NoMatchSingular {
            get {
                return ResourceManager.GetString("NoMatchSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitably annotated title property on class: {0}.
        /// </summary>
        public static string NoTitleAnnotation {
            get {
                return ResourceManager.GetString("NoTitleAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of keys provided does not match the number of keys specified for type: {0}.
        /// </summary>
        public static string NumberOfkeysMismatch {
            get {
                return ResourceManager.GetString("NumberOfkeysMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be assigned to: {1}.
        /// </summary>
        public static string ObjectCannotBeAssigned {
            get {
                return ResourceManager.GetString("ObjectCannotBeAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object has multiple properties with suffix: {0}.
        /// </summary>
        public static string ObjectMultiplePropertiesMessage {
            get {
                return ResourceManager.GetString("ObjectMultiplePropertiesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object has no properties with suffix: {0}.
        /// </summary>
        public static string ObjectNoPropertiesMessage {
            get {
                return ResourceManager.GetString("ObjectNoPropertiesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query would produce {0} objects. Only the first {1} will be shown.
        /// </summary>
        public static string QueryFilterMessage {
            get {
                return ResourceManager.GetString("QueryFilterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title property: {0} on class: {1} must be a string to find by title.
        /// </summary>
        public static string TitlePropertyWrongType {
            get {
                return ResourceManager.GetString("TitlePropertyWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: {0} cannot be found.
        /// </summary>
        public static string TypeCannotBeFound {
            get {
                return ResourceManager.GetString("TypeCannotBeFound", resourceCulture);
            }
        }
    }
}
